"""Add AI training data models

Revision ID: 7d936f1f64d7
Revises: 2a5a9ea01389
Create Date: 2026-01-22 16:13:19.799128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d936f1f64d7'
down_revision: Union[str, Sequence[str], None] = '2a5a9ea01389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('short_term_analysis', sa.Text(), nullable=True),
    sa.Column('mid_term_analysis', sa.Text(), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('resistance_level', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('price_at_analysis', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_symbol_time', 'ai_analyses', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_symbol'), 'ai_analyses', ['symbol'], unique=False)
    op.create_table('ai_training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('future_price_1h', sa.Float(), nullable=True),
    sa.Column('future_price_4h', sa.Float(), nullable=True),
    sa.Column('future_price_24h', sa.Float(), nullable=True),
    sa.Column('label_1h', sa.Integer(), nullable=True),
    sa.Column('label_4h', sa.Integer(), nullable=True),
    sa.Column('label_24h', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_symbol_time', 'ai_training_data', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_training_data_id'), 'ai_training_data', ['id'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candle_symbol_time', 'market_candles', ['symbol', 'timeframe', 'open_time'], unique=False)
    op.create_index(op.f('ix_market_candles_id'), 'market_candles', ['id'], unique=False)
    op.create_table('signal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('price_at_signal', sa.Float(), nullable=False),
    sa.Column('executed', sa.Integer(), nullable=True),
    sa.Column('price_after_1h', sa.Float(), nullable=True),
    sa.Column('price_after_4h', sa.Float(), nullable=True),
    sa.Column('price_after_24h', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('profit_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_history_id'), 'signal_history', ['id'], unique=False)
    op.create_index(op.f('ix_signal_history_symbol'), 'signal_history', ['symbol'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sma_5', sa.Float(), nullable=True),
    sa.Column('sma_10', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_width', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicator_symbol_time', 'technical_indicators', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_index('idx_indicator_symbol_time', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_signal_history_symbol'), table_name='signal_history')
    op.drop_index(op.f('ix_signal_history_id'), table_name='signal_history')
    op.drop_table('signal_history')
    op.drop_index(op.f('ix_market_candles_id'), table_name='market_candles')
    op.drop_index('idx_candle_symbol_time', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_ai_training_data_id'), table_name='ai_training_data')
    op.drop_index('idx_training_symbol_time', table_name='ai_training_data')
    op.drop_table('ai_training_data')
    op.drop_index(op.f('ix_ai_analyses_symbol'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_index('idx_analysis_symbol_time', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
